POST http://localhost:3000/user/create HTTP/1.1
content-type: application/json

{
    "genero": "Masculino",
    "idade": "20",
    "nome": "Jhonatan"
}

###

GET http://localhost:3000/user/read HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/user/show/1 HTTP/1.1
content-type: application/json

{
    "genero": "Masculino",
    "idade": "20",
    "nome": "Marcius"
}

###

DELETE http://localhost:3000/user/delete/1 HTTP/1.1
content-type: application/json